[tox]
envlist =
    py{310,311,312,313,314}-django52-{sqlite,mysql,postgresql}
    py{311,312,313,314}-django60-{sqlite,mysql,postgresql}
    py{310,311,312}-django42-{sqlite,mysql,postgresql}
    qa
    docs
skip_missing_interpreters = True
sitepackages = False

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
usedevelop = true
commands =
    mysql: mysql -u root -h {env:DB_HOST} --password={env:DB_PASSWORD} --protocol tcp -e 'drop database if exists test_dbdiff_test;'
    postgresql: psql -U postgres -h {env:DB_HOST}  -c 'drop database if exists test_dbdiff_test;'
    pytest -vv --cov dbdiff --create-db --strict -r fEsxXw {posargs:dbdiff}
allowlist_externals =
    mysql
    psql
deps =
    pytest
    pytest-django
    pytest-cov
    mock
    coverage
    django52: Django>=5.2,<6.0
    django60: Django>=6.0,<6.1
    django42: Django>=4.2,<5.0
    postgresql: psycopg2-binary==2.9.9
    mysql: mysqlclient
setenv =
    PIP_ALLOW_EXTERNAL=true
    DJANGO_SETTINGS_MODULE=dbdiff.tests.project.settings
    sqlite: DJANGO_SETTINGS_MODULE=dbdiff.tests.project.settings_sqlite
    postgresql: DJANGO_SETTINGS_MODULE=dbdiff.tests.project.settings_postgresql
    postgresql: DB_NAME=dbdiff_test
    postgresql: DB_ENGINE=postgresql_psycopg2
    postgresql: DB_USER=postgres
    mysql: DJANGO_SETTINGS_MODULE=dbdiff.tests.project.settings_mysql
    mysql: DB_NAME=dbdiff_test
    mysql: DB_ENGINE=mysql
    mysql: DB_USER=root
passenv =
    TEST_*
    DBDIFF_*
    DB_*
    PGPASSWORD

[testenv:qa]
basepython = python3.12
commands =
    ruff check dbdiff
deps =
    ruff

[testenv:docs]
basepython = python3.12
usedevelop = true
commands =
    sphinx-build -W -b html docs docs/_build/html
deps =
    sphinx
    Django>=4.2,<5.0
setenv =
    DJANGO_SETTINGS_MODULE=dbdiff.tests.project.settings_sqlite
